apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
spec:
  volumeName: etcd-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

